export const experienceEvents = [
  {
    date: "Jan. 2018 – April 2018",
    content: "JR Support Officer ",
    company: "@Immigration, Refugees and Citizenship Canada",
    side: "right",
    link: "https://www.canada.ca/en/immigration-refugees-citizenship.html",
  },
  {
    date: "Sept. 2018 – Dec. 2018",
    content: "Software Developer ",
    company: "@Ribbon Communications",
    side: "left",
    link: "https://ribboncommunications.com/",
  },
  {
    date: "May 2019 – Dec. 2019",
    content: "Database Developer ",
    company: "@University of Ottawa",
    side: "right",
    link: "https://www.uottawa.ca",
  },
  {
    date: "May 2020 – Aug. 2020",
    content: "Web Developer ",
    company: "@University of Ottawa",
    side: "left",
    link: "https://www.uottawa.ca",
  },
  {
    date: "Jan. 2021 – Jan. 2022",
    content: "Web Developer ",
    company: "@freelance",
    side: "right",
    link: "",
  },
  {
    date: "Jan. 2022 – Present",
    content: "Web Developer ",
    company: "@Noterro",
    side: "left",
    link: "https://www.noterro.com/",
  },
];

export const skillsItems = [
  {
    title: "Languages",
    items: ["JavaScript", "PHP", "HTML", "CSS", "SQL", "Java", "Python"],
  },
  {
    title: "Frameworks",
    items: [
      "React",
      "CakePHP",
      "Tailwind CSS",
      "Jest",
      "Material UI",
      "Laravel",
      "Vue.js",
      "PHPUnit",
      "Bootstrap",
      "Symfony",
    ],
  },
  {
    title: "Other",
    items: [
      "GitHub",
      "React Context",
      "Redux",
      "MERN Stack",
      "VS Code",
      "Postman",
      "Agile",
      "Jira",
      "Firebase",
      "PostgreSQL",
      "MySQL",
      "PhpStorm",
      "Amazon EC2",
      "MVC",
      "Eclipse",
      "Linux",
    ],
  },
];
